# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/51abfb7b-42a2-401b-9c85-51a845d1f4f7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A14-AC21";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/claudia" =
    { device = "/dev/disk/by-uuid/6b49ede1-0b20-4b7d-8d4a-b7fd75ac6a65";
      fsType = "ext4";
    };

  fileSystems."/mnt/linux-tera2" =
    { device = "/dev/disk/by-uuid/c79a0f37-a3ef-490e-a3bb-ff3d16aabfeb";
      fsType = "ext4";
    };

  fileSystems."/mnt/linux-tera" =
    { device = "/dev/disk/by-uuid/b90231ac-c7c0-4569-b605-924df5591a02";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8c7fa8ff-295f-4828-95a6-24f991ea5b54"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
